export interface VersionRelease {
  version: string
  date: string
  codename?: string
  changes: string[]
}

export const APP_VERSION = "v2.3.37"
export const APP_BUILD = "2026.09.23"
export const APP_NAME = "IT-THINGS 98"
export const APP_EDITION = "Second Edition (SE)"

export const APP_CHANGELOG: VersionRelease[] = [
  {
    version: "v2.3.37",
    date: "23 Sep 2026",
    codename: "Wordle 98 Category Hint Polish & Two Daily Quizzes",
    changes: [
      "Penyederhanaan Hint Wordle 98: Menghapus kisi-kisi teks dan huruf awal, memfokuskan petunjuk hanya pada Kategori kata agar permainan tetap menantang.",
      "Dua Kuis Harian Terpisah (Kuis 1 & Kuis 2): Pemain dapat memainkan dua kata rahasia berbeda per hari dengan switcher retro dan tombol cepat lanjut ke kuis berikutnya.",
      "Panel Callout Hint Retro: Desain banner petunjuk kategori khas Windows 98 yang ringkas dan ramah tampilan mobile.",
    ],
  },
  {
    version: "v2.3.36",
    date: "22 Sep 2026",
    codename: "Tower 98 Altitude Dynamics & Wordle Two Quizzes Hint",
    changes: [
      "Fix Fisika Tower 98 (Stabilisasi Lantai Tinggi): Memperbaiki bug false game-over pada menara tinggi dengan scaling timeout jatuh dinamis dan grace period kontak lantai bawah.",
      "Efek Angin & HUD Kompas Win98 (Lantai 5+): Menambahkan hembusan angin dinamis yang mendorong balok saat jatuh secara realistis, dilengkapi visual wind streaks dan indikator HUD retro.",
      "Atmosfer Langit Bertahap: Ketinggian menara kini mengubah latar belakang secara dinamis dari Siang Cerah (1-5F), Sunset Lembayung (6-12F), Starry Night Berbintang (13-20F), hingga Orbit Luar Angkasa (21F+).",
      "Milestone Ketinggian: Perayaan visual dan banner khusus saat mencapai lantai 5F, 10F, 15F, 20F, 25F, dan 30F dengan feedback audio dan skor ekstra.",
      "Wordle 98 Hint & Dua Kuis Harian: Peningkatan petunjuk kata dan format kuis harian pada modul Wordle.",
    ],
  },
  {
    version: "v2.3.35",
    date: "21 Sep 2026",
    codename: "Billiard 98 Mode Vs AI (Lawan Bot Komputer)",
    changes: [
      "Fitur Main Lawan Bot (Vs AI): Pemain kini dapat bertanding biliar melawan komputer secara offline langsung dari lobby tanpa perlu menunggu pemain lain.",
      "Algoritma Bot Murni TypeScript (ai-bot.ts): Menggunakan kalkulasi ghost ball vector, raycasting pengecekan rintangan, dan filter cut angle untuk memilih sudut tembakan terbaik.",
      "3 Tingkat Kesulitan Bot: Tersedia pilihan level Pemula (🟢 Easy), Handal (🟡 Medium), dan Master (🔴 Hard) dengan variasi toleransi deviasi sudut dan pengaturan power.",
      "Animasi Membidik & Tarik Stik Realistis: Siklus giliran bot dilengkapi jeda berpikir, animasi stik mengarah ke sudut bidikan, tarikan stik mundur sesuai power, serta dukungan auto ball-in-hand.",
      "Indikator Status & Personality Bot: Menampilkan ikon bot khusus pada Player 2, badge tingkat kesulitan, status aktivitas bot realtime di reaction bar, serta komentar/reaksi retro dari bot.",
    ],
  },
  {
    version: "v2.3.34",
    date: "17 Sep 2026",
    codename: "Billiard 98 Room Lock, Opponent Aim View, Auto Chat Broadcast & Locked Window",
    changes: [
      "Lock Room Multiplayer (Anti-Double Join): Room Billiard yang sudah memiliki 2 pemain (in_game) kini otomatis terkunci, ditampilkan sebagai Penuh (2/2) di lobby, dan menolak pemain ke-3 secara otomatis.",
      "Tampilkan Stik Lawan Realtime (Opponent Cue Aiming): Saat menunggu giliran lawan, pemain kini dapat melihat rotasi stik lawan, tarikan power mundur, dan garis bidik kuning emas khas secara langsung di atas meja.",
      "Auto-Post Notifikasi Room ke Chat Umum: Saat pemain membuat room Billiard baru atau memulai pertandingan Paint War, pesan pengumuman otomatis terkirim ke Chat Umum untuk mengajak teman kantor bermain.",
      "Lock Window Billiard: Jendela POOL98.EXE dikembalikan ke ukuran tetap (fixed retro size) agar tata letak meja dan antarmuka biliar tetap kokoh dan stabil.",
    ],
  },
  {
    version: "v2.3.33",
    date: "17 Sep 2026",
    codename: "Billiard 98 Resizable Window, Minimum Constraints & Focus Lock",
    changes: [
      "Window Resizing 8 Arah: Jendela POOL98.EXE kini dapat diubah ukurannya secara bebas dari tepi manapun (atas, bawah, kiri, kanan, serta 4 sudut) lengkap dengan grip retro diagonal khas Windows 98 di pojok kanan bawah.",
      "Skala Meja Dinamis & Proporsional: Kanvas meja biliar dan rasio aspek 856:456 otomatis menyesuaikan ukuran jendela secara proporsional dan responsif tanpa terpotong maupun gepeng saat di-resize atau di-maximize.",
      "Batas Ukuran Minimal Aman (minWidth: 680, minHeight: 480): Jendela tidak dapat diperkecil melebihi batas minimal meja biliar untuk menjaga keterbacaan bola, garis bidik, dan kenyamanan kontrol stik.",
      "Disable Tombol Minimize (_): Tombol minimize dinonaktifkan khusus jendela Billiard untuk mencegah jendela tertutup atau ter-minimize secara tidak sengaja saat pertandingan sedang berlangsung.",
      "Double-Click Title Bar: Mendukung klik ganda pada title bar untuk toggle Maximize dan Restore secara instan.",
    ],
  },
  {
    version: "v2.3.32",
    date: "17 Sep 2026",
    codename: "Billiard 98 Ball-in-Hand Freedom & Realtime Anti-False Disconnect Polish",
    changes: [
      "Bebas Pindahkan Bola Putih (Ball-in-Hand): Pemain kini dapat mengklik di mana saja di atas meja atau melakukan drag bebas untuk meletakkan bola putih.",
      "Algoritma Auto-Snap Titik Legal (findClosestValidCuePlacement): Posisi bola putih otomatis digeser secara halus ke titik legal terdekat jika terlalu dekat bantalan atau bola lain tanpa pernah membatalkan penempatan.",
      "Banner Aksi 'Siap Tembak' & Power Slider Langsung: Ditambahkan tombol konfirmasi 'Siap Tembak' serta dukungan menarik power slider langsung saat ball-in-hand untuk langsung mengunci posisi dan menembak.",
      "Reset Status Animasi Bola Masuk: Membersihkan pocketAnimationProgress saat scratch dan penempatan bola agar bola putih tidak pernah terkunci dalam kondisi masuk lubang.",
      "Stabilisasi Channel Realtime & Grace Period 15 Detik: Mencegah trigger leave palsu saat update posisi bola dan memberikan tenggat 15 detik bagi lawan yang koneksinya sempat terputus sebelum memvonis WO.",
    ],
  },
  {
    version: "v2.3.31",
    date: "17 Sep 2026",
    codename: "Billiard 98 Pro (8 Ball Pool Online, 3D Rolling, Reactions, Leaderboard & Auto WO Win)",
    changes: [
      "Billiard 98 (POOL98.EXE): Game biliar 8-Ball retro Windows 98 lengkap dengan Room Lobby multiplayer realtime, matchmaking online, dan mode lokal (Pass & Play).",
      "Fisika 3D Natural & Replikasi 8 Ball Pool: Rotasi gulir bola 3D Rodrigues dengan dual-pole badges, efek sabuk pita stripe sferis melengkung, cue ball spin control (top/back/sidespin), aim ghost ball guideline, dan zero-lag smooth cue dragging.",
      "Emoji Spectator Reaction & Quick Chat: Tombol reaksi cepat mengambang (floating emoji), tabbed chat popup (20 emoji + frasa obrolan cepat), dan efek suara retro synthesizer Web Audio API.",
      "Papan Klasemen Tim (billiard_leaderboard): Peringkat 50 pemain terbaik dengan podium medali Top 3, statistik win rate, streak kemenangan, rating poin, dan sinkronisasi otomatis via Supabase Realtime.",
      "Deteksi Walkover (WO) & Disconnect Auto-Win: Kemenangan otomatis bagi pemain yang bertahan saat lawan tiba-tiba menutup browser/tab atau menyerah di mode multiplayer online, dengan pencatatan rekor klasemen instan.",
      "Custom Retro Icon: Ikon retro kustom meja biliar kayu mahogany dengan bola 8 hitam 3D dan stik kapur biru di taskbar, title bar, dan menu launcher.",
    ],
  },
  {
    version: "v2.3.30",
    date: "14 Sep 2026",
    codename: "Snipper.exe QA Studio Pro, AI Background Remover & Retro Bug Icon",
    changes: [
      "Snipper.exe (QA Bug & Screenshot Studio): Aplikasi desktop baru dengan Tool Anotasi Lengkap (Pilih, Crop, Teks Bebas, Panah, Kotak, Spotlight Dimmer, Stabilo Transparan, Step Counter #1 #2, Callout Bubble, Sensor Blackout, Pixelate, dan Stempel Status).",
      "Interactive Resize & Properties Bar: Resize bebas teks dan bentuk objek via handle retro di kanvas (NW/NE/SE/SW, ujung panah, ekor callout) serta bar properti dinamis (stepper font, presets, tebal garis, edit teks langsung).",
      "Before vs After Comparison Studio: Studio perbandingan gambar Expected vs Actual dengan mode Berdampingan (Side-by-Side) dan mode Curtain Slider Diff interaktif.",
      "AI Background Remover (BG_REMOVE.EXE): Utilitas baru di SwissTools (kategori Media & Gambar) untuk menghapus latar foto 100% lokal di browser via WebAssembly tanpa kirim data ke server.",
      "Ikon Bug Retro & Keep-Alive State: Logo desktop & taskbar Snipper diganti ikon Bug Beetle retro, serta integrasi keepMountedOnMinimize dan persistent tab agar kanvas tidak ter-reset saat berpindah jendela.",
    ],
  },
  {
    version: "v2.3.29",
    date: "14 Sep 2026",
    codename: "Paint War Game Concepts Upgrade, Match Lobby Setup & Dual Scoring System",
    changes: [
      "Lobby Setup Sebelum Start (SETTING_LOBBY.EXE): Menyediakan panel pengaturan match retro Windows 98 untuk memilih target ronde (3, 5, 8, 10), durasi waktu gambar (45s, 60s, 90s), dan filter bank kata (Campuran, IT & Tech, Kultur Kantor, Umum) sebelum pertandingan dimulai.",
      "Sistem Dua Skor (Sesi vs Akumulasi All-Time): Memisahkan skor sesi ronde saat ini dengan total akumulasi poin karir sepanjang masa di Supabase, lengkap dengan filter sorting di papan skor.",
      "Penyempurnaan Deteksi Tebakan: Mendukung normalisasi spasi tanpa sensitivitas spasi berlebih serta deteksi tebakan 'hampir benar' (Levensthein distance & substring) dengan petunjuk inline retro.",
      "Realtime Presence & Kontrol Ronde Terintegrasi: Menampilkan status online pemain standby di lobby, pergantian giliran cepat jika drawer offline, dan penghentian permainan otomatis saat batas ronde tercapai.",
    ],
  },
  {
    version: "v2.3.28",
    date: "14 Sep 2026",
    codename: "Accurate Prayer Schedule Sound & Vocal Adzan at Scheduled Time",
    changes: [
      "Ketepatan Suara Notifikasi & Adzan: Memindahkan bunyi suara notifikasi dan adzan tepat saat menit jadwal sholat tiba, bukan lagi 5 menit sebelum.",
      "Koreksi Penentuan Waktu Pas Sholat: Memperbaiki pencarian jadwal sholat sehingga saat menit jadwal tiba (diff 0 menit), status sholat aktif terdeteksi tepat waktu.",
      "Pengingat Persiapan H-5 Menit Hening: Pengingat 5 menit sebelum sholat (dan 10 menit sholat Jumat) tetap muncul sebagai balon teks Clippy tanpa bunyi suara yang mengganggu.",
    ],
  },
  {
    version: "v2.3.27",
    date: "14 Sep 2026",
    codename: "Media & Video Grabber in Swiss Army Tools (MEDIA_GRAB.EXE)",
    changes: [
      "Media & Video Grabber (MEDIA_GRAB.EXE): Utilitas unduh media langsung dari TikTok (video HD no-watermark & audio MP3) dan Twitter/X (MP4) tanpa iklan.",
      "Penempatan Paling Atas di SwissTools: Kategori 'Media & Downloader' kini menjadi tab default paling atas saat membuka SwissTools.",
      "UI Sleek & Minimalis: Desain retro Windows 98 yang ringkas dengan tombol Paste instan, pratinjau thumbnail otomatis, dan indikator status platform.",
      "Informasi Pembatasan YouTube: Deteksi cerdas tautan YouTube dengan informasi edukatif mengenai proteksi bot server.",
    ],
  },
  {
    version: "v2.3.26",
    date: "14 Sep 2026",
    codename: "PDF Processing Web Worker Buffer Cloning & Detached ArrayBuffer Fix",
    changes: [
      "Perbaikan Detached ArrayBuffer: Mengkloning ArrayBuffer dengan aman via .slice() pada helper loadPdfDocument sebelum ditransfer ke Web Worker PDF.js.",
      "Resiliensi Buffer Kompresi & Split: Menjamin pengambilan buffer segar langsung dari berkas lokal (file.arrayBuffer()) saat proses kompresi dan ekspor split PDF berjalan.",
    ],
  },
  {
    version: "v2.3.25",
    date: "14 Sep 2026",
    codename: "PDF_COMPRESS.EXE Client-Side PDF Compressor with Smart Presets & Live Comparison",
    changes: [
      "Modul Baru PDF_COMPRESS.EXE: Utilitas kompresi berkas PDF 100% client-side di Swiss Army Tools untuk mengecilkan ukuran dokumen tanpa kirim data ke server luar.",
      "Tiga Level Preset Kompresi: Pilihan Rekomendasi (keseimbangan terbaik ~50%-75%), Ekstrem (ukuran terkecil untuk batas portal < 1MB), dan Ringan (kualitas tajam).",
      "Komparasi Ukuran Sebelum vs Sesudah: Tampilan metrik Before vs After dan persentase penghematan ukuran file secara real-time.",
      "Pratinjau Hasil & Auto-Download: Integrasi penampil PREVIEW_DOKUMEN.EXE untuk cek dokumen asli maupun hasil kompresi sebelum/sesudah unduh otomatis.",
      "Proteksi Dokumen 3-Lapis: Pengaman unsaved guard browser beforeunload, konfirmasi pindah tool, dan penutupan jendela desktop.",
    ],
  },
  {
    version: "v2.3.24",
    date: "14 Sep 2026",
    codename: "Swiss Army Tools PDF Suite, Document Previewer & Unsaved Changes Guard",
    changes: [
      "PDF Merge (PDF_MERGE.EXE): Penggabungan multi-file PDF client-side dengan cover thumbnail otomatis, pengaturan urutan berkas, estimasi jumlah halaman, dan pratinjau dokumen langsung di dalam aplikasi.",
      "PDF Split & Organize (PDF_SPLIT.EXE): Visual thumbnail canvas per lembar dokumen, rotasi 90° interaktif, filter/seleksi rentang halaman (range), serta ekspor ke 1 PDF utuh atau arsip ZIP berkas terpisah.",
      "PDF & Image Converter (PDF_CONV.EXE): Konversi dua arah gambar ke PDF (JPG/PNG/WebP dengan pengaturan margin dan orientasi A4) dan ekstraksi lembar PDF ke gambar berkualitas tinggi (satuan atau ZIP).",
      "Interactive Document Viewer (PREVIEW_DOKUMEN.EXE): Penampil dokumen modal ala Windows 98 dengan navigasi lembar (Prev/Next/Jump), kontrol zoom in/out/100%, dan cache render cepat.",
      "Sistem Pengaman Dokumen (3-Tier Unsaved Guard): Proteksi cegah kehilangan antrean berkas via event beforeunload browser, konfirmasi pindah tool di SwissTools, dan konfirmasi penutupan jendela desktop.",
    ],
  },
  {
    version: "v2.3.23",
    date: "14 Sep 2026",
    codename: "FEEDBACK.EXE Suggestion Box, Bug Reporting System, Anonymous Submissions & Realtime Upvotes",
    changes: [
      "Modul Baru FEEDBACK.EXE: Aplikasi desktop terintegrasi untuk mengumpulkan saran, kritik, ide fitur, dan pelaporan bug tim internal dengan tampilan retro Windows 98.",
      "Mode Anonim & Privasi Terjamin: Pengguna dapat mengirim masukan secara rahasia tanpa nama/avatar (disanitasi di level server action untuk mencegah data leak).",
      "Sistem Dukungan (Upvote) Realtime: Anggota tim dapat memberikan upvote untuk ide favorit, langsung tersinkronisasi antar pengguna via Supabase Realtime.",
      "Tracking Status & Tanggapan Admin: Pelacakan alur pengerjaan (Baru, Ditinjau, Diproses, Selesai, Ditutup) lengkap dengan catatan respon resmi dari Admin IT.",
      "Integrasi Desktop & Start Menu: Ikon desktop FEEDBACK.EXE dan menu pintas instan 'Kirim Feedback & Saran...' di Start Menu.",
    ],
  },
  {
    version: "v2.3.22",
    date: "14 Sep 2026",
    codename: "Custom Profile Photo Upload, Supabase Storage Bucket & Client-Side Auto-Crop",
    changes: [
      "Fitur Upload Foto Profil (PROFILE.EXE): Pengguna kini dapat mengunggah foto profil kustom (JPG, PNG, WebP, GIF) langsung dari jendela edit profil atau klik pada avatar preview.",
      "Supabase Storage Bucket & RLS: Penyimpanan foto profil terpusat di bucket 'avatars' Supabase dengan kebijakan Row Level Security (RLS) terisolasi untuk integritas dan keamanan data tim.",
      "Server Action Upload: Integrasi upload server-side (uploadProfilePhotoAction) via Server Actions Next.js yang memvalidasi otorisasi dan format berkas secara ketat tanpa mengekspos endpoint atau skema database internal.",
      "Client-Side 1:1 Auto-Crop & WebP Compression: Pemrosesan gambar otomatis di sisi browser menggunakan HTML5 Canvas, memastikan foto terpotong rapi di tengah (square) dan terkompresi di bawah 40KB untuk loading super cepat dan hemat kuota.",
      "Dukungan Mode Tamu (Guest) & Transisi Mulus: Penyimpanan avatar kustom berbasis data URL lokal untuk mode tamu, serta kemudahan berganti kapan saja antara Foto Kustom, Preset Retro, Foto Google, atau Inisial.",
    ],
  },
  {
    version: "v2.3.21",
    date: "14 Sep 2026",
    codename: "Persistent Pomodoro Engine, Browser Refresh Resilience & Desktop State Preservation",
    changes: [
      "Persistent Pomodoro Engine: Memindahkan logika timer & state ke root provider (PomodoroProvider) berbasis timestamp riil (targetEndTimestamp), membuat timer berjalan presisi dan kebal terhadap background tab throttling maupun window minimize.",
      "Browser Refresh Resilience: Status timer (berjalan/pause), sisa detik, dan mode aktif kini tersimpan otomatis di localStorage. Saat browser di-refresh (F5), timer tidak mengulang dari nol (25:00), melainkan langsung melanjutkan detik berjalan secara mulus atau mempertahankan waktu pause.",
      "Desktop State & URL Routing Preservation: Jendela Pomodoro.exe kini otomatis mengingat status terbukanya saat browser di-refresh, serta menambahkan 'pomodoro' dan 'swisstools' ke daftar aplikasi valid desktop routing (?app=pomodoro).",
    ],
  },
  {
    version: "v2.3.20",
    date: "13 Sep 2026",
    codename: "Pomodoro.exe Focus & Ergonomic Stretching App, Tomato Pixel Icon, Supabase Session Sync & Weekly Activity Chart",
    changes: [
      "Peluncuran Pomodoro.exe (pomodoro.exe): Aplikasi timer produktivitas tim IT yang menggabungkan teknik Pomodoro klasik (Deep Work 25m/50m, Short Break 5m, Long Break 15m) dengan panduan peregangan otot ergonomis.",
      "Panduan Ergonomi & Peregangan Otot (Anti-Jompo): 6 gerakan peregangan terstruktur (bahu & dada anti-bungkuk, pergelangan tangan anti-CTS/carpal tunnel, leher kaku, rotasi lumbar/pinggang, istirahat mata 20-20-20, dan hidrasi air putih) lengkap dengan mini timer interaktif.",
      "Visualisasi Grafik Aktivitas 7 Hari (Weekly Bar Chart): Tab Riwayat & Grafik menyajikan grafik batang vertikal CRT retro membandingkan porsi menit fokus (biru) dan peregangan (hijau) per hari serta kartu metrik jam produktif.",
      "Sinkronisasi Database Supabase & Background Timer: Pencatatan riwayat sesi otomatis tersinkron ke tabel Supabase (pomodoro_sessions) via Server Actions aman, sisa waktu fokus tersimpan independen saat ganti tab, serta keepMountedOnMinimize agar timer tetap berjalan lancar di latar belakang.",
      "Ikon Tomat Pixel-Art Retro & Integrasi Clippy: Desain aset vektor pixel-art tomat retro (tomato.svg) di seluruh desktop, titlebar jendela, taskbar, dan Start menu, dipadukan dengan synthesizer nada chime Web Audio API dan dialog pengingat santai dari asisten Clippy.",
    ],
  },
  {
    version: "v2.3.19",
    date: "13 Sep 2026",
    codename: "Clippy-Only Desktop Assistant, Authentic Vocal Adzan & Adaptive H-5/H-10 Pre-Adzan Reminder",
    changes: [
      "Clippy-Only Desktop Assistant: Menghapus opsi karakter Meril Wizard dan Rover Dog, mengunci asisten desktop secara paten ke Clippy 98 otentik serta merampingkan dialog pengaturan jadwal sholat.",
      "Suara Adzan Vokal Asli: Mengganti efek beeps buatan dengan rekaman audio adzan vokal asli berkualitas tinggi (Adzan Masjidil Haram Makkah, Adzan Masjid Nabawi Madinah, Syaikh Mishary Rashid Alafasy, Adzan Nusantara Melayu, Bedug Tradisional, dan Lonceng Digital Masjid).",
      "Interactive Sound Preview: Menambahkan tombol pratinjau putar/stop interaktif pada panel pengaturan suara adzan di JADWAL_SHOLAT.EXE.",
      "Pengingat Persiapan Adaptif (H-5 Menit Biasa, H-10 Menit Jumatan): Menyesuaikan alarm persiapan sholat menjadi 5 menit sebelum adzan untuk sholat harian biasa, serta khusus 10 menit sebelum waktu Sholat Jumat dengan ucapan pengingat masjid yang kontekstual.",
    ],
  },
  {
    version: "v2.3.18",
    date: "13 Sep 2026",
    codename: "SwissTools.exe IT Swiss Army Knife, Multi-Timezone Converter & Desktop Two-Column Layout",
    changes: [
      "Peluncuran SwissTools.exe (tools.exe): Modul utilitas harian teknis tim IT yang berjalan 100% offline & client-side tanpa risiko kebocoran data ke server.",
      "8 Utilitas Teknis Esensial: Termasuk JSON Formatter & Validator (prettify, minify, auto-fix quotes), JWT Inspector (parsing header/payload/signature & live expiration countdown), Hash Generator (MD5, SHA-1, SHA-256, SHA-512 & checksum matcher), Base64 & URL Encoder/Decoder, UUID v4 & NanoID generator, Case Converter (camelCase, snake_case, kebab-case, dll.), dan Regex Tester dengan capture groups.",
      "Konversi Waktu & Zona Dunia (TIME_CONV.EXE): Ticker epoch realtime detik/ms, konversi bolak-balik Timestamp <-> Tanggal WIB/UTC/ISO, perbandingan serentak 10 zona waktu dunia dalam ListView Windows 98, serta kalkulator durasi & selisih waktu.",
      "Penataan Ulang Desktop Grid (2 Kolom Seimbang): Penyesuaian grid desktop ke grid-rows-6 sehingga seluruh 11 ikon tersusun rapi dalam 2 kolom vertikal tanpa kolom ke-3 yang ganjil di layar mobile, serta penamaan file tools.exe yang tidak terpotong.",
    ],
  },
  {
    version: "v2.3.17",
    date: "13 Sep 2026",
    codename: "Tower 98 Physics Game, Anti-Spam Drop, Varied Citizen Inhabitants & Difficulty Levels",
    changes: [
      "Peluncuran Game Tower 98 (TOWER.EXE): Game susun menara retro berbasis fisika Planck.js (Box2D) dengan crane berayun, efek getaran gedung bertingkat, dan rekor combo.",
      "Tingkat Kesulitan Fisika (Santai / Normal / Ekstrim): Menambahkan 3 mode level kesulitan yang dapat dipilih dari dialog awal maupun header toolbar. Mode Santai menawarkan redaman goyangan tinggi (angularDamping: 0.75) dan ayunan tenang agar menara tidak mudah oleng.",
      "Penghuni Warga Masuk Lantai (Random Variatif): Setiap lantai yang berhasil mendarat stabil diramaikan warga kota pixel art lucu yang masuk dengan cara acak (terjun payung berayun, terbang balon gas, meluncur roket jetpack 98, ngebut skateboard di balkon, atau lari). Jendela menyala hangat dan warga menetap di dalamnya.",
      "Pencegahan Exploit Enter-Spam: Crane spawn dari pinggir layar secara bergantian (kiri/kanan via cosine motion) dengan arming window 250ms, memastikan spam tombol Enter langsung jatuh meleset dan gugur.",
      "Leaderboard Harian Supabase & UI Polish: Papan peringkat harian tersinkronisasi ke database Supabase (tower_daily_scores), Retro LED Digital Scoreboard (Skor, Warga, Lantai), dialog Windows 98 terstandarisasi, dan ikon desktop SVG kustom untuk TOWER.EXE dan PAINT.EXE.",
    ],
  },
  {
    version: "v2.3.16",
    date: "13 Sep 2026",
    codename: "Server Actions Migration, DevTools Inspect Shield & Master Desktop Bootstrap",
    changes: [
      "Server Actions Migration: Migrasi fetch data Chat, Team, Wordle, Memo, PIC, dan Lapak ke Next.js Server Actions ('use server'), mengeliminasi keterpaparan nama tabel database Supabase dan route API pada tab Network Inspect Element.",
      "Master Desktop Bootstrap: Mengonsolidasikan inisialisasi awal desktop (Badges Vote, Pantry, Kas, Split Bill, Paint War, Memo, PIC, Lapak, serta Unread Chat Count) ke dalam 1 panggilan Server Action tunggal (getDesktopBootstrapAction).",
      "Database Soft-Delete Privacy & Auto-Sanitize: Sanitasi 33 pesan terhapus historis dan pemasangan trigger database Postgres otomatis (trg_chat_message_soft_delete) untuk meredaksi konten pesan dan menghapus reaksi terkait saat pesan di-soft-delete.",
      "Standardisasi Dokumen Arsitektur: Menambahkan aturan standar Server-Side Fetching & Network Privacy (Anti-Inspect Leak) ke dalam AGENTS.md.",
    ],
  },
  {
    version: "v2.3.15",
    date: "13 Sep 2026",
    codename: "Supabase Key Resolution, Live Team Sync, Dummy Data Purge & Chat Video Card Enhancement",
    changes: [
      "Supabase Server Key Resolution: Perbaikan urutan pembacaan key di lib/server/supabase-server.ts yang memprioritaskan NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY dan memfilter placeholder dummy ('...'), memperbaiki kendala HTTP 500 pada route /api/team.",
      "Live Team Directory & Dummy Data Purge: Menghapus total DEFAULT_MEMBERS dummy lokal (Budi Santoso, Citra Lestari, Dimas Pratama, Eko Prasetyo) di lib/team-store.ts dan membersihkan legacy cache localStorage, sehingga team.exe langsung menampilkan 20 anggota tim asli secara live dari Supabase.",
      "Sanitasi Fallback Demo Lapak: Menjaga DEMO_LAPAK_ITEMS di lib/lapak-store.ts agar tidak menimpa listing asli saat Supabase telah terhubung.",
      "Peningkatan Chat & Pratinjau Video YouTube: Kartu judul YouTube pada chat sekarang menjadi tautan langsung yang dapat diklik membuka video di tab baru, serta pembersihan format judul pada pesan lagu Winamp.",
      "Otomatisasi Release Workflow Skill: Memperbarui prosedur release (.agents/skills/release) dengan standardisasi pre-flight mandatory npm run build, typecheck, bump version, changelog, dan git push.",
    ],
  },
  {
    version: "v2.3.14",
    date: "12 Sep 2026",
    codename: "Chat Live Links, Quick Copy, Anti-Prank Video Title & Winamp Auto-Detect",
    changes: [
      "Auto-Detect & Clickable Live Links: Setiap tautan URL http/https di obrolan chat otomatis aktif sebagai link yang dapat diklik langsung dengan pemisahan tanda baca rapi.",
      "Tombol Salin Link 1-Klik: Ditambahkan tombol retro mini [Salin] di samping tautan dengan indikator feedback [Tersalin!] selama 2 detik.",
      "Kartu Pratinjau Judul Video YouTube (Anti-Prank / Anti-Rickroll): Menampilkan card judul resmi dan nama kanal YouTube pada setiap link obrolan sebelum dibuka atau diputar.",
      "Tombol Putar Cepat di Winamp: Akses 1-klik [▶ Putar di Winamp] langsung dari balon chat yang otomatis memasukkan lagu ke playlist dan membuka jendela WINAMP.EXE.",
      "Auto-Resolve & Metadata Cache Winamp: Deteksi otomatis judul video saat paste link ke form Winamp, sinkronisasi judul asli pada pesan 'Share ke Chat', serta client-side caching.",
    ],
  },
  {
    version: "v2.3.13",
    date: "12 Sep 2026",
    codename: "Welcome 98 What's New Hub & Start Pointer Balloon",
    changes: [
      "Peluncuran modul Welcome 98 (welcome98.exe) untuk pengumuman otomatis pembaruan sistem dan highlight fitur baru.",
      "Showcase 4 fitur utama: Winamp 2.91 & CRT, Game Center 98, Status Online Tim, dan Properti Wallpaper dengan tombol peluncur langsung.",
      "Balon Petunjuk Retro Windows 98 yang menunjuk ke tombol Start di taskbar dengan animasi pulse amber saat pengumuman selesai dibaca.",
      "Integrasi menu What's New pada Start Menu, menu klik kanan desktop (Context Menu), dan dialog winver.exe.",
      "Sanitasi event keyboard: isolasi tombol Escape khusus dialog tanpa mencegat Enter pada form login dan input teks.",
    ],
  },
  {
    version: "v2.3.12",
    date: "12 Sep 2026",
    codename: "Winamp 2.91 Media Player with CRT Video Display & 2-Way Sync",
    changes: [
      "Peluncuran aplikasi pemutar media retro Winamp 2.91 (winamp.exe) dengan green LCD marquee, spectrum equalizer, volume control, dan drawer playlist.",
      "Layar CRT Video Display (AVS) dengan 4 filter retro: CRT 90s scanlines, VHS Tape OSD, Matrix Green Terminal, dan Normal.",
      "Input Cepat & Standby Terminal Langsung di Layar CRT: Memungkinkan paste link YouTube langsung di tengah monitor tanpa perlu scroll.",
      "Sinkronisasi 2-Arah via YouTube IFrame API: Slider volume Winamp mengontrol volume YouTube real-time, serta aksi pause/play langsung di video tersinkronisasi otomatis ke Winamp.",
      "Spektrum Equalizer Reaktif: Animasi bar spektrum yang merespons volume suara dan langsung rata saat di-pause atau di-mute.",
      "Dialog Konfirmasi Hapus Retro: Menggunakan standar ConfirmDialog (HAPUS_LAGU.EXE dan KOSONGKAN_PLAYLIST.EXE) dengan RetroActionButton.",
      "Integrasi Shortcut Desktop & Taskbar Ticker: Shortcut Winamp dan Wordle di desktop serta running track ticker di taskbar.",
    ],
  },
  {
    version: "v2.3.11",
    date: "12 Sep 2026",
    codename: "Server-Side Anti-Cheat, Team Privacy & In-Flight Request Deduplication",
    changes: [
      "Arsitektur Anti-Cheat Server-Side Wordle 98: Memindahkan 200+ bank kata dan kalkulasi harian ke server-only module, serta validasi tebakan via route handlers (/api/wordle/today & /api/wordle/guess).",
      "Sanitasi Papan Skor Wordle: Implementasi PostgreSQL view public.wordle_leaderboard di Supabase untuk mengisolasi riwayat tebakan (guesses) pemain lain dari network response.",
      "Team Member Privacy & Email Masking: Proxy data tim melalui /api/team dan /api/team/[id] dengan pembatasan akses email hanya untuk akun Administrator.",
      "Pembersihan Legacy Fridge: Menghapus total query, counter badge, dan subscription realtime fridge_items yang tidak digunakan.",
      "In-Flight Request Deduplication: Penerapan shared in-memory caching & request deduplication pada pic-store, lapak-store, wordle-store, team-store, dan memo-store untuk mereduksi duplikasi fetch pada saat mount desktop.",
    ],
  },
  {
    version: "v2.3.10",
    date: "12 Sep 2026",
    codename: "Daily Wordle 98 Asynchronous Word Puzzle & Mobile Responsive Polish",
    changes: [
      "Peluncuran game harian asinkron Wordle 98 (wordle.exe): tebak 1 kata rahasia 5 huruf tiap hari (reset jam 00:00) santai tanpa harus online bersamaan.",
      "Integrasi 200+ kosakata kurasi istilah IT, kultur kantor IT-Things, dan bahasa Indonesia 5-huruf valid.",
      "Papan Klasemen Harian realtime terintegrasi Supabase yang mencatat ranking tebakan tersedikit dan waktu selesai anggota tim.",
      "Fitur Salin Hasil Emoji retro khas Wordle untuk dibagikan ke obrolan tim atau chat messenger.",
      "Dukungan input ganda: keyboard fisik komputer (A-Z, Enter, Backspace) dan keyboard virtual touch-friendly di layar.",
      "Optimasi tampilan mobile untuk Wordle 98: touch-manipulation, hit area tombol min 32px, dan tata letak responsif.",
      "Penyempurnaan state launcher desktop dengan auto-fallback data instance agar aplikasi game selalu terbuka lancar.",
    ],
  },
  {
    version: "v2.3.9",
    date: "12 Sep 2026",
    codename: "Multiplayer Paint War 98, Retro Game Arcade & Exit Confirmation",
    changes: [
      "Peluncuran game multiplayer Paint War 98 (paintwar.exe): tebak gambar live realtime bergaya MS Paint dengan 16 palet warna Win98, flood fill, undo, dan word bank istilah IT & kantor.",
      "Integrasi Game Center (game.exe) sebagai launcher koleksi game retro tim menggantikan posisi ikon team.exe di desktop.",
      "Perbaikan normalisasi resolusi ikon retro pada RetroIcon component untuk mencegah error load asset PNG.",
      "Penambahan interceptor konfirmasi keluar retro (ConfirmDialog KELUAR_GAME.EXE) saat tombol close ditekan agar sesi permainan tidak sengaja tertutup.",
      "Pembersihan status kehadiran online (is_online) secara otomatis saat pemain menutup game atau browser untuk mencegah ghost player.",
      "Optimalisasi broadcast goresan gambar (throttling 50ms) dan debounced canvas snapshot ke Supabase Realtime.",
    ],
  },
  {
    version: "v2.3.8",
    date: "12 Sep 2026",
    codename: "Mobile Responsive Overhaul — Taskbar, Pantry Card View & Auth Modals",
    changes: [
      "Taskbar mobile: ticker promo, badge versi, nama & role user disembunyikan di layar < md agar tidak terpotong.",
      "Pantry katalog: tampilan card list khusus mobile (< sm) menggantikan tabel — stok, progress kuota, dan tombol ambil nyaman di-tap.",
      "Tab navigasi Pantry kini scrollable horizontal (overflow-x-auto) dan tidak wrapping di layar sempit.",
      "Google Login Modal: tambah tombol close (×) di title bar dengan touch target min 32px.",
      "global.css: overflow-x hidden + overscroll-behavior none untuk mencegah horizontal scroll tak disengaja.",
      "RetroActionButton: hit area icon mode diperluas ke minimal 32px untuk kenyamanan tap mobile.",
      "Sticky note widget: batas posisi dan max-width diperbaiki agar tidak menimpa ikon desktop di viewport sempit.",
    ],
  },
  {
    version: "v2.3.7",
    date: "12 Sep 2026",
    codename: "Split Bill Suite, Realtime Database Sync & Deterministic Member Order",
    changes: [
      "Peluncuran modul Split Bill (splitbill.exe) dengan kalkulasi otomatis (bagi rata & itemized), ongkir, pajak, dan diskon.",
      "Integrasi Supabase Realtime & RLS: izin kelola eksklusif untuk Pembuat Sesi dan Admin.",
      "Pembersihan otomatis data tagihan setelah 7 hari via pg_cron untuk menjaga performa database.",
      "Format input nominal otomatis dengan masking titik Rupiah dan opsi simpan rekening default per pengguna.",
      "Kunci urutan peserta deterministik dan stabil agar daftar anggota tidak meloncat saat konfirmasi pembayaran.",
    ],
  },
  {
    version: "v2.3.6",
    date: "12 Sep 2026",
    codename: "Internet Explorer 98, Pantry Navigation Split & Clean Counter Badges",
    changes: [
      "Peluncuran aplikasi Internet Explorer (iexplore.exe) dengan YouTube video player retro, background audio persistence, pencarian video, dan preset kategori.",
      "Pemisahan navigasi pemilih bulan di Pantry ke Tab Rekap dan Riwayat, mengunci Tab Katalog pada konsumsi bulan berjalan secara real-time.",
      "Standarisasi badge counter notifikasi ikon desktop (Vote, Pantry) menjadi angka ringkas polos tanpa embel-embel teks.",
      "Perbaikan handling virtual keyboard dan taskbar viewport pada perangkat mobile.",
      "Integrasi skill workflow otomatisasi rilis untuk percepatan build, versioning, commit, dan push.",
    ],
  },
  {
    version: "v2.3.5",
    date: "11 Sep 2026",
    codename: "Aesthetic Wallpaper Expansion & Mobile Chat Polish",
    changes: [
      "Ekspansi galeri Display Properties dengan 21 preset wallpaper beresolusi tinggi (Retro 98, Aesthetic & Scene, Modern Gradient).",
      "Kategori filter interaktif pada Properti Tampilan untuk mempermudah pemilihan tema wallpaper.",
      "Optimasi tampilan mobile untuk jendela desktop dan chat input mengikuti viewport virtual keyboard.",
      "Perbaikan urutan React Hook pada Display Properties dialog untuk stabilitas render.",
      "Operasi hening tanpa efek suara retro saat minimize/restore desktop dan ganti wallpaper.",
    ],
  },
  {
    version: "v2.3.4",
    date: "11 Sep 2026",
    codename: "Kas Google Sheets Portal & Dues Mechanism",
    changes: [
      "Integrasi portal resmi Google Spreadsheet pada Kas.exe dengan direct launch tab baru dan tombol salin link cepat.",
      "Pengumuman mekanisme iuran resmi divisi IT dengan tarif berjenjang (TKO: Rp 100.000, TKNO: Rp 50.000) dan jadwal gajian (tgl 8 & 25).",
      "Pembersihan form transaksi lokal dan dummy ledger agar pencatatan terpusat 100% pada Google Sheets.",
      "Pelepasan flag isComingSoon pada Kas.exe untuk peluncuran resmi dari Desktop dan Start Menu.",
      "Perbaikan layout card tarif iuran retro Windows 98 agar rapi, proporsional, dan bebas wrapping teks berlebih.",
    ],
  },
  {
    version: "v2.3.3",
    date: "11 Sep 2026",
    codename: "Display Properties & Show Desktop Suite",
    changes: [
      "Fitur Quick Launch toolbar di Taskbar dengan tombol Show Desktop (Minimize & Restore Semua Jendela) otentik Windows 98 serta shortcut Alt+D.",
      "Fitur kustomisasi wallpaper desktop ala Windows 98 (Display Properties / desk.cpl).",
      "Preview visual monitor CRT tabung interaktif real-time dengan efek scanline dan simulasi ikon desktop.",
      "Koleksi preset retro legendaris (Windows 98 Classic Teal, Windows 2000 Pro Blue, Matrix Terminal, XP Bliss, Synthwave, dll).",
      "Dukungan kustomisasi lengkap: upload berkas gambar lokal otomatis kompresi, URL gambar web, dan palet warna solid hex.",
      "Menu klik kanan retro (Context Menu) pada area desktop kosong untuk akses instan ke Properti Tampilan dan Show Desktop.",
      "Penyimpanan preferensi persisten di browser (localStorage) dengan mode tampilan (Fill, Fit, Tile, Center) serta toggle efek tekstur & watermark.",
    ],
  },
  {
    version: "v2.3.2",
    date: "11 Sep 2026",
    codename: "Lapak Teman & Smart Rupiah Price Masking",
    changes: [
      "Modul Lapak_Teman.exe untuk katalog promosi usaha, jastip, kuliner, dan jasa IT rekan tim dengan integrasi direct WhatsApp.",
      "Running Ticker Marquee emas retro (Glowing Gold LED Ticker) di Taskbar dengan highlight promo berputar dan pause-on-hover.",
      "Tab Lapak Teman pada widget Sticky Note desktop dengan kartu promo mini dan navigasi carousel.",
      "Input harga cerdas dengan auto-masking titik Rupiah realtime (Harga Pas, Mulai Dari, Rentang Min-Max, Nego/Custom).",
      "Penyelarasan icon harga netral (Price Tag 🏷️) menggantikan simbol dollar.",
    ],
  },
  {
    version: "v2.3.1",
    date: "11 Sep 2026",
    codename: "Chat Realtime Resilience & Mute Protocol",
    changes: [
      "Sinkronisasi otomatis obrolan chat lintas perangkat saat tab aktif kembali, bangun dari sleep, dan online (visibilitychange/focus).",
      "Bridge event realtime dari channel notifikasi global ke store obrolan untuk mencegah chat out-of-sync.",
      "Penanganan sesi token Supabase kedaluwarsa dengan auto-refresh & auto-retry otomatis pada pengiriman pesan.",
      "Perbaikan fitur mode Bisu: menonaktifkan suara retro, menyenyapkan suara native Windows OS (silent: true), dan menahan pop-up notifikasi.",
    ],
  },
  {
    version: "v2.3.0",
    date: "11 Sep 2026",
    codename: "Dynamic Multi-PIC & Lapak Usaha Suite",
    changes: [
      "Sistem penunjukan Dynamic Multi-PIC (PIC Kas & PIC Pantry) dengan delegasi realtime langsung dari antarmuka Team App.",
      "Penghapusan static role Bendahara (treasurer) dan standarisasi ke peran bersih Admin & Member berdasar hak akses PIC dinamis.",
      "Modul Lapak Teman (lapak.exe) untuk etalase dan promosi usaha kuliner/jasa internal tim dengan taskbar running ticker.",
      "Optimasi responsive layout form penunjukan PIC dan perbaikan batas overflow pada elemen retro Windows 98.",
    ],
  },
  {
    version: "v2.2.6",
    date: "11 Sep 2026",
    codename: "Desktop Sticky Note Announcement",
    changes: [
      "Fitur Desktop Sticky Note (MEMO.TXT) untuk papan pengumuman tim interaktif di wallpaper desktop.",
      "Dukungan drag & drop bebas dengan penyimpanan posisi koordinat otomatis di browser (localStorage).",
      "Sinkronisasi realtime via Supabase Realtime dengan proteksi role (hanya Admin dan Bendahara yang dapat mengedit).",
      "Normalisasi format baris baru (newline) dan tombol reset posisi ke default.",
    ],
  },
  {
    version: "v2.2.5",
    date: "10 Sep 2026",
    codename: "Single Reaction Enforcer",
    changes: [
      "Pembatasan reaksi pesan obrolan maksimal satu emoji per pengguna (enforced via database unique constraint).",
      "Otomatis mengganti (replace) emoji sebelumnya saat pengguna memilih emoji berbeda.",
      "Mendukung toggle off / menghapus reaksi jika mengklik emoji yang sama.",
      "Penambahan listener realtime UPDATE dan policy Row-Level Security pada chat_reactions.",
    ],
  },
  {
    version: "v2.2.4",
    date: "10 Sep 2026",
    codename: "Onboarding & README System Guide",
    changes: [
      "Penambahan aplikasi Notepad retro (README.txt) di desktop dengan panduan lengkap pengenalan IT-THINGS.",
      "Panel interaktif ringkasan fungsi web ('Web ini untuk apa?') di layar Passcode sebelum login.",
      "Badge status INFO pada ikon README.txt dan penataan ulang grid ikon desktop.",
      "Penyempurnaan branding & tagline portal di wallpaper desktop dan layar security gate.",
    ],
  },
  {
    version: "v2.2.3",
    date: "10 Sep 2026",
    codename: "LiveChat Security & Input Sanitization",
    changes: [
      "Sanitasi ketat input teks chat untuk mencegah pesan kosong, spasi/enter saja, dan Unicode zero-width/invisible chars.",
      "Database CHECK constraint pada tabel chat_messages & chat_reactions di Supabase (max 1000 char, no empty space).",
      "Penghitung karakter real-time di textarea dengan batas tegas maksimal 1000 karakter.",
      "Proteksi anti-flood cooldown pada pengiriman pesan obrolan.",
      "Validasi keamanan URL avatar (hanya protokol aman) & pencegahan ReDoS pada regex mention.",
    ],
  },
  {
    version: "v2.2.2",
    date: "10 Sep 2026",
    codename: "Desktop Icon Activity Badges",
    changes: [
      "Badge chip retro pada ikon desktop Vote.exe jika ada polling/vote aktif.",
      "Badge chip retro dengan animasi pulse pada ikon desktop Chat.exe jika ada pesan belum dibaca.",
      "Sinkronisasi realtime untuk jumlah vote aktif dan unread chat lintas jendela.",
      "Perbaikan integritas hak akses Admin (database & client) agar penghapusan/moderasi pesan chat selalu berfungsi.",
    ],
  },
  {
    version: "v2.2.1",
    date: "10 Sep 2026",
    codename: "Windows OS Notifications & Auto-Permission",
    changes: [
      "Permintaan izin notifikasi browser otomatis saat unlock passcode dan interaksi pertama.",
      "Banner pemicu perizinan notifikasi di header Chat.exe untuk kemudahan aktivasi manual.",
      "Notifikasi native Windows OS (Action Center) aktif saat obrolan baru masuk.",
    ],
  },
  {
    version: "v2.2.0",
    date: "10 Sep 2026",
    codename: "Retro Notification Suite",
    changes: [
      "Fitur notifikasi in-app retro (balon pop-up Windows 98 di pojok taskbar).",
      "Efek suara retro chime ding sintetis via Web Audio API tanpa aset eksternal.",
      "Kontrol mute/bisu di System Tray Taskbar dan header Chat.exe.",
      "Indikator unread badge & animasi kedip pada tombol taskbar Chat.exe.",
    ],
  },
  {
    version: "v2.1.1",
    date: "10 Sep 2026",
    codename: "Mobile Chat & Admin Moderation",
    changes: [
      "Perbaikan hak akses admin & policy RLS untuk moderasi/hapus pesan di Chat.exe.",
      "Peningkatan UX Chat di mobile: interaksi tap-to-activate & floating action toolbar di atas pesan.",
      "Penyempurnaan posisi popover emoji reaksi agar tidak terpotong di layar HP.",
      "Peningkatan lapisan z-index dialog konfirmasi agar selalu tampil di depan pada mobile.",
    ],
  },
  {
    version: "v2.1.0",
    date: "10 Sep 2026",
    codename: "Chat & Security Gate",
    changes: [
      "Fitur Live Team Chat (Chat.exe) realtime dengan mention, reaksi emoji, & edit pesan.",
      "Passcode Security Gate 4-digit & mode akses Tamu (Read-Only).",
      "Edit Profil & Sinkronisasi Nama/Avatar internal.",
      "Dialog Tentang Sistem (winver.exe) & tampilan versioning terpusat.",
    ],
  },
  {
    version: "v2.0.0",
    date: "1 Sep 2026",
    codename: "Retro Desktop Suite",
    changes: [
      "Perombakan antarmuka bergaya Windows 98 Retro Desktop.",
      "Modul Vote.exe dengan sinkronisasi Supabase Realtime.",
      "Taskbar retro, Start menu, window manager multi-tasking.",
      "Indikator konektivitas live/demo & fallback local storage.",
    ],
  },
  {
    version: "v1.0.0",
    date: "15 Agu 2026",
    codename: "Initial Release",
    changes: [
      "Rilis perdana aplikasi utilitas internal tim IT.",
      "Manajemen grup polling dan voting dasar.",
    ],
  },
]
